version: '3'

services:
  resources:
    build:
      context: ./
      dockerfile: ./Dockerfile

    container_name: jenkins

    # ポート設定 (ホストポート:仮想ポート)
    ports:
      - "8889:8080"

    # ホストのディレクトリ:マウント先のディレクトリ
    volumes:
      - ./mnt/jenkins_home:/var/jenkins_home